[package]
name = "mosaicterm-bin"
version = "0.1.0"
edition = "2021"
authors = ["MosaicTerm Team"]
description = "Binary for MosaicTerm GUI terminal emulator"
license = "MIT OR Apache-2.0"

[dependencies]
# Local library
mosaicterm = { path = "../../mosaicterm-lib" }

# GUI Framework
egui.workspace = true
eframe.workspace = true

# Async Runtime (needed for app.rs)
tokio.workspace = true
futures.workspace = true

# Time handling (needed for demo commands)
chrono.workspace = true

# Utility
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
